server:
  port: 8080
spring:
  data:
    redis:
      database: 4
      host: 127.0.0.1
      port: 6379
      timeout: 5000                     # 连接超时时间(5秒)
      password: 200500
      jedis:
        pool:
          max-active: 500               # 最大活跃连接数
          max-idle: 100                 # 最大空闲连接数
          min-idle: 20                  # 最小空闲连接数
          max-wait: 3000

